#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ll="ls -l"
alias updatedb="sudo /usr/libexec/locate.updatedb"
alias grep="ggrep --color"
alias find="gfind"
alias make="gmake"
alias utc="gdate --utc"